### ISSUE TITLE
Getting weight of choice for ResponseQuestion

### ISSUE THREAD

**Issue by saboehnke** [bcemmett/SurveyMonkeyApi-v3#11] opened 2016-10-26 18:54 UTC
I have a MatrixRatingAnswer that has 5 possible choices. (5 stars). Of these 5 choices only the lowest and highest have text for their names. These 2 show up in the code when I try to get the string value Choice from the response. I do not get anything for the other 3 choices. I am trying to find something in the code that will let me access the weight of each choice so I can figure out what was chosen if it is not the highest or lowest choice. Is this possible?

**Comment by bcemmett** [comment] 2016-11-13 21:29
Closing as duplicate of #13

**Closed by bcemmett** 2016-11-13 21:29 UTC
